sudo: required
install: true
services:
  - docker

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

script:
- |
  set -e
    docker build -t langrisha/keybase:latest .
    docker run --rm langrisha/keybase:latest keybase status
